"""Alembic migration script template."""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '431c39943fb5'
down_revision = '8b58af50c6c8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('item_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False))
    op.add_column('orders', sa.Column('price', sa.Float(), nullable=False))
    op.alter_column('orders', 'description',
               existing_type=sa.VARCHAR(length=512),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'description',
               existing_type=sa.VARCHAR(length=512),
               nullable=False)
    op.drop_column('orders', 'price')
    op.drop_column('orders', 'item_name')
    # ### end Alembic commands ###
