"""Alembic migration script template."""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '845b76521e38'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sites',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=False),
    sa.Column('accountable_user_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sites_accountable_user_id'), 'sites', ['accountable_user_id'], unique=False)
    op.create_index(op.f('ix_sites_id'), 'sites', ['id'], unique=False)
    op.create_index(op.f('ix_sites_name'), 'sites', ['name'], unique=False)
    op.create_table('suppliers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('company_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('contact_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_suppliers_company_name'), 'suppliers', ['company_name'], unique=False)
    op.create_index(op.f('ix_suppliers_email'), 'suppliers', ['email'], unique=False)
    op.create_index(op.f('ix_suppliers_id'), 'suppliers', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('phone_number', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'SITE_ACCOUNTABLE', 'PROCUREMENT', 'TECHNICIAN', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('site_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_site_id'), 'users', ['site_id'], unique=False)
    op.create_foreign_key('fk_sites_accountable_user_id_users', 'sites', 'users', ['accountable_user_id'], ['id'])
    op.create_table('inventory_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('main_category', sa.Enum('SPARE_PARTS', 'TOOLS', 'SAFETY_EQUIPMENT', name='maincategory'), nullable=False),
    sa.Column('sub_category', sa.Enum('INVERTER', 'DC_CABLE', 'AC_CABLE', 'PANEL', 'BREAKER', 'CLAMP_METER', 'AVO_METER', 'FIRST_AID_KIT', 'SAFETY_HARNESS', 'OTHER', name='subcategory'), nullable=False),
    sa.Column('model_number', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('supplier_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_items_id'), 'inventory_items', ['id'], unique=False)
    op.create_index(op.f('ix_inventory_items_main_category'), 'inventory_items', ['main_category'], unique=False)
    op.create_index(op.f('ix_inventory_items_model_number'), 'inventory_items', ['model_number'], unique=False)
    op.create_index(op.f('ix_inventory_items_name'), 'inventory_items', ['name'], unique=False)
    op.create_index(op.f('ix_inventory_items_sub_category'), 'inventory_items', ['sub_category'], unique=False)
    op.create_index(op.f('ix_inventory_items_supplier_id'), 'inventory_items', ['supplier_id'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=False),
    sa.Column('status', sa.Enum('REQUESTED', 'APPROVED', 'REJECTED', 'RECEIVED', name='orderstatus'), nullable=False),
    sa.Column('supplier_id', sa.Uuid(), nullable=False),
    sa.Column('site_id', sa.Uuid(), nullable=True),
    sa.Column('created_by_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_created_by_id'), 'orders', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_orders_id'), 'orders', ['id'], unique=False)
    op.create_index(op.f('ix_orders_site_id'), 'orders', ['site_id'], unique=False)
    op.create_index(op.f('ix_orders_status'), 'orders', ['status'], unique=False)
    op.create_index(op.f('ix_orders_supplier_id'), 'orders', ['supplier_id'], unique=False)
    op.create_table('inventory_stock',
    sa.Column('site_id', sa.Uuid(), nullable=False),
    sa.Column('item_id', sa.Uuid(), nullable=False),
    sa.Column('quantity_available', sa.Integer(), nullable=False),
    sa.Column('quantity_faulty', sa.Integer(), nullable=False),
    sa.Column('min_safety_threshold', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('min_safety_threshold >= 0', name='ck_min_threshold_non_negative'),
    sa.CheckConstraint('quantity_available >= 0', name='ck_qty_available_non_negative'),
    sa.CheckConstraint('quantity_faulty >= 0', name='ck_qty_faulty_non_negative'),
    sa.ForeignKeyConstraint(['item_id'], ['inventory_items.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('site_id', 'item_id')
    )
    op.create_table('transfer_requests',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source_site_id', sa.Uuid(), nullable=False),
    sa.Column('target_site_id', sa.Uuid(), nullable=False),
    sa.Column('item_id', sa.Uuid(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('REQUESTED', 'APPROVED', 'IN_TRANSIT', 'RECEIVED', 'CANCELLED', name='transferstatus'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('quantity > 0', name='ck_transfer_quantity_positive'),
    sa.CheckConstraint('source_site_id != target_site_id', name='ck_transfer_sites_differ'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['inventory_items.id'], ),
    sa.ForeignKeyConstraint(['source_site_id'], ['sites.id'], ),
    sa.ForeignKeyConstraint(['target_site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transfer_requests_created_by'), 'transfer_requests', ['created_by'], unique=False)
    op.create_index(op.f('ix_transfer_requests_id'), 'transfer_requests', ['id'], unique=False)
    op.create_index(op.f('ix_transfer_requests_item_id'), 'transfer_requests', ['item_id'], unique=False)
    op.create_index(op.f('ix_transfer_requests_source_site_id'), 'transfer_requests', ['source_site_id'], unique=False)
    op.create_index(op.f('ix_transfer_requests_status'), 'transfer_requests', ['status'], unique=False)
    op.create_index(op.f('ix_transfer_requests_target_site_id'), 'transfer_requests', ['target_site_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transfer_requests_target_site_id'), table_name='transfer_requests')
    op.drop_index(op.f('ix_transfer_requests_status'), table_name='transfer_requests')
    op.drop_index(op.f('ix_transfer_requests_source_site_id'), table_name='transfer_requests')
    op.drop_index(op.f('ix_transfer_requests_item_id'), table_name='transfer_requests')
    op.drop_index(op.f('ix_transfer_requests_id'), table_name='transfer_requests')
    op.drop_index(op.f('ix_transfer_requests_created_by'), table_name='transfer_requests')
    op.drop_table('transfer_requests')
    op.drop_table('inventory_stock')
    op.drop_index(op.f('ix_orders_supplier_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_status'), table_name='orders')
    op.drop_index(op.f('ix_orders_site_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_created_by_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_inventory_items_supplier_id'), table_name='inventory_items')
    op.drop_index(op.f('ix_inventory_items_sub_category'), table_name='inventory_items')
    op.drop_index(op.f('ix_inventory_items_name'), table_name='inventory_items')
    op.drop_index(op.f('ix_inventory_items_model_number'), table_name='inventory_items')
    op.drop_index(op.f('ix_inventory_items_main_category'), table_name='inventory_items')
    op.drop_index(op.f('ix_inventory_items_id'), table_name='inventory_items')
    op.drop_table('inventory_items')
    op.drop_index(op.f('ix_users_site_id'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_suppliers_id'), table_name='suppliers')
    op.drop_index(op.f('ix_suppliers_email'), table_name='suppliers')
    op.drop_index(op.f('ix_suppliers_company_name'), table_name='suppliers')
    op.drop_table('suppliers')
    op.drop_index(op.f('ix_sites_name'), table_name='sites')
    op.drop_index(op.f('ix_sites_id'), table_name='sites')
    op.drop_index(op.f('ix_sites_accountable_user_id'), table_name='sites')
    op.drop_table('sites')
    # ### end Alembic commands ###
