"""Alembic migration script template."""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '8b58af50c6c8'
down_revision = '845b76521e38'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'supplier_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('orders', 'site_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'site_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('orders', 'supplier_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
